### ISSUE TITLE
need requirements

### ISSUE THREAD

**Issue by unikcc** [DeepGraphLearning/SPN#4]
Hi, I can't run the code successfuly, since the versions of python, cuda and packages like tocch-geometric are mysterious.
Could you please provide an environment configuration that could support to run the code? Thank you!

**Comment by unikcc** [comment]
Another Question: 
In [23-th line of `dataset.py`](https://github.com/DeepGraphLearning/SPN/blob/main/dataset.py#:~:text=data.edge_index_reversed%20%3D%20edge_dict%5Bv%2C%20u%5D), `data.edge_index_reversed = edge_dict[v, u]`  Why it is 
`data.edge_index_reversed = edge_dict[v, u]`
instead of 
`data.edge_index_reversed = edge_dict[u, v]`
According to [18-th line of dataset.py](https://github.com/DeepGraphLearning/SPN/blob/main/dataset.py#:~:text=u%2C%20v%20%3D%20data.edge_index),  `u, v = data.edge_index`,
u is row indices, and v is column indices, isn't it? I'm a little confused.

**Comment by mnqu** [comment]
Thanks for your interest in our work and sorry about the late response.

I think it should be fine as long as the version of torch-geometric is 1.X.X. You could find an environment configuration in the attached file.
[spn.txt](https://github.com/DeepGraphLearning/SPN/files/8764464/spn.txt)

**Comment by unikcc** [comment]
Ok, thank you~ I'll try.
